routes/web.php
<?php

use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [FrontendController::class, 'index'])->name('home');
Route::get('/blogs/tags/{tag}', [FrontendController::class, 'tags'])->name('tag.blogs');
Route::get('/blogs/category/{category}', [FrontendController::class, 'category'])->name('category.blogs');

/**
 * Admin Panel Routes
 */

Route::middleware(['auth'])->group(function() {
    Route::resource('categories', CategoriesController::class);
    Route::resource('tags', TagsController::class);
    Route::resource('posts', PostsController::class);
    Route::get('/trashed/posts', [PostsController::class, 'trashed'])->name('posts.trashed');

    Route::get('/dashboard', function () {
        return view('admin.dashboard');
    })->name('dashboard');
});
Route::middleware(['auth', 'admin'])->group(function() {
    Route::get('/users', [UsersController::class, 'index'])->name('users.index');
    Route::put('/users/{user}/make-admin', [UsersController::class, 'makeAdmin'])->name('users.makeAdmin');
});



require __DIR__.'/auth.php';

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
    protected $fillable = [
        'name'
    ];

    /**
     * ACCESSOR TO RETURN POST COUNT RELATED TO CATEGORY
     */

    public function getPostsCountAttribute(){
        return $this-> posts()->count();
    }

    /**
     * RELATIONSHIP METHODS
     */
    public function posts() {
        return $this->hasMany(Post::class);

    }
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{
    public function index()
    {
        $categories = Category::all();
        return view('admin.categories.index', compact(['categories']));
    }
    public function create()
    {
         return view('admin.categories.create');
    }
    public function store(Request $request)
    {
         try{
           Category::create(['name' => $request->name]);
           return redirect(route('categories.index'))
                ->with(['status' => 'success',
                    'message' => 'Category Added Successfully!'
                ]);

         }catch(\Exception $e){
            return redirect(route('categories.index'))
            ->with(['status' => 'danger',
                'message' => 'OOPS! Something went wrong!'
            ]);

         }
    }
    public function show(Category $category)
    {

    }
    public function edit(Category $category)
    {
        return view('admin.categories.edit', compact(['category']));
    }
    public function update(Request $request, Category $category)
    {
//        $category->name = $request->name;
//        $category->save();
        $category->update(['name'=>$request->name]);
        return redirect(route('categories.index'))->with(
            [
                'status' => 'success',
                'message' => 'Category Updated Successfully!'
            ]
        );
    }



    public function destroy(Category $category)
    {
        if($category->posts()->count()>0){
            return redirect(route('categories.index'))->with(
                [
                    'status' => 'danger',
                    'message' => 'Category Has Posts! Cannot Delete'
                ]
            );

         }
        $category->delete();
        return redirect(route('categories.index'))->with(
            [
                'status' => 'success',
                'message' => 'Category Has been deleted!'
            ]
        );

    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.app')

@section('main-content')
    <div class="row">
        <div class="col-md-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Add New Category</h6>
                </div>
                <div class="card-body">
                    <form action="{{route('categories.store')}}"method="POST">
                        @csrf
                        <div class="form-group">
                            <label for="name" class="form-label">Name</label>
                            <input type="text" class="form-control"name="name">
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-success">Add</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.app')

@section('main-content')
    <div class="row">
        <div class="col-md-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Edit Category</h6>
                </div>
                <div class="card-body">
                    <form action="{{route('categories.update',$category->id)}}"method="POST">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="name" class="form-label">Name</label>
                            <input type="text" class="form-control"name="name" value="{{ $category->name }}">
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-success">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.app')

@section('main-content')
    <div class="row">
        <div class="col-md-12">
            <div class="float-right mb-3">
                <a href="{{ route('categories.create') }}" class="btn btn-primary">Add New Category</a>
            </div>
        </div>
        <div class="col-md-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Categories</h6>
                </div>
                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                            <th>Id</th>
                            <th>Name</th>
                            <th>Actions</th>
                        </thead>
                        <tbody>
                            @foreach($categories as $category)
                                <tr>
                                    <td>{{ $category->id }}</td>
                                    <td>{{ $category->name }}</td>
                                    <td>
                                        <a href="{{ route('categories.edit', $category->id) }}" class="btn btn-info btn-sm">Edit</a>
                                        <button class="btn btn-danger btn-sm delete" data-bs-toggle="modal" data-bs-target="#deleteModal" data-category-id="{{ $category->id }}">Delete</button>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <!-- Delete Confirmation Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Modal title</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to delete?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <form id="deleteForm" method="POST">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger">Yes, Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        document.querySelectorAll('.delete').forEach(function (btn) {
            btn.addEventListener('click', handleDeleteClick);
        });

        function handleDeleteClick(evt) {
            const categoryId = evt.target.dataset.categoryId;
            const URL = `/categories/${categoryId}`;
            document.getElementById('deleteForm').setAttribute('action', URL);
        }
    </script>
@endsection