routes/web.php
<?php

use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [FrontendController::class, 'index'])->name('home');
Route::get('/blogs/tags/{tag}', [FrontendController::class, 'tags'])->name('tag.blogs');
Route::get('/blogs/category/{category}', [FrontendController::class, 'category'])->name('category.blogs');

/**
 * Admin Panel Routes
 */

Route::middleware(['auth'])->group(function() {
    Route::resource('categories', CategoriesController::class);
    Route::resource('tags', TagsController::class);
    Route::resource('posts', PostsController::class);
    Route::get('/trashed/posts', [PostsController::class, 'trashed'])->name('posts.trashed');

    Route::get('/dashboard', function () {
        return view('admin.dashboard');
    })->name('dashboard');
});
Route::middleware(['auth', 'admin'])->group(function() {
    Route::get('/users', [UsersController::class, 'index'])->name('users.index');
    Route::put('/users/{user}/make-admin', [UsersController::class, 'makeAdmin'])->name('users.makeAdmin');
});



require __DIR__.'/auth.php';

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    use HasFactory;
    protected $fillable = [
        'name'
    ];
    /**
     * RELATIONSHIP METHODS
     */
    public function posts() {
        return $this->belongsToMany(Post::class)->withTimestamps();

    }
}

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Tag;
use Illuminate\Http\Request;

class TagsController extends Controller
{
    public function index()
    {
        $tags = Tag::all();
        return view('admin.tags.index', compact(['tags']));
    }

    public function create()
    {
        return view('admin.tags.create');
    }

    public function store(Request $request)
    {
        Tag::create(['name' => $request->name]);
        session()->flash('status', 'success');
        session()->flash('message', 'Tag added successfully!');
        return redirect(route('tags.index'));
    }

    public function edit(Tag $tag)
    {
        return view('admin.tags.edit', compact(['tag']));
    }

    public function update(Request $request, Tag $tag)
    {
        $tag->update(['name' => $request->name]);
        session()->flash('status', 'success');
        session()->flash('message', 'Tag updated successfully!');
        return redirect(route('tags.index'));
    }

    public function destroy(Tag $tag)
    {
        if($tag->posts()->count() > 0) {
            session()->flash('status', 'danger');
            session()->flash('message', 'Tag has Posts! Cannot Delete');
            return redirect(route('tags.index'));
        }

        $tag->delete();
        session()->flash('status', 'success');
        session()->flash('message', 'Tag deleted successfully!');
        return redirect(route('tags.index'));
    }
}

resources/views/admin/tags/create.blade.php
@extends('admin.layouts.app')

@section('main-content')
    <div class="row">
        <div class="col-md-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Add New Tag</h6>
                </div>
                <div class="card-body">
                    <form action="{{ route('tags.store') }}"method="POST">
                        @csrf
                        <div class="form-group">
                            <label for="name" class="form-label">Name</label>
                            <input type="text" class="form-control"name="name">
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-success">Add</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/tags/edit.blade.php
@extends('admin.layouts.app')

@section('main-content')
    <div class="row">
        <div class="col-md-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Edit Tag</h6>
                </div>
                <div class="card-body">
                    <form action="{{ route('tags.update', $tag) }}"method="POST">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="name" class="form-label">Name</label>
                            <input type="text" class="form-control" name="name" value="{{ $tag->name }}">
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-success">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/tags/index.blade.php
@extends('admin.layouts.app')

@section('main-content')
    <div class="row">
        <div class="col-md-12">
            <div class="float-right mb-3">
                <a href="{{ route('tags.create') }}" class="btn btn-primary">Add New Tag</a>
            </div>
        </div>
        <div class="col-md-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Tags</h6>
                </div>
                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                            <th>Id</th>
                            <th>Name</th>
                            <th>Actions</th>
                        </thead>
                        <tbody>
                            @foreach($tags as $tag)
                                <tr>
                                    <td>{{ $tag->id }}</td>
                                    <td>{{ $tag->name }}</td>
                                    <td>
                                        <a href="{{ route('tags.edit', $tag) }}" class="btn btn-info btn-sm">Edit</a>
                                        <button data-tag-id="{{ $tag->id }}" class="btn btn-danger btn-sm delete" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <!-- Delete Confirmation Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Modal title</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to delete?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <form action="" id="deleteForm" method="POST">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger">Yes, Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        document.querySelectorAll('.delete').forEach(function (btn) {
            btn.addEventListener('click', handleDeleteClick);
        })

        function handleDeleteClick(evt) {
            const tagId = evt.target.dataset.tagId;
            const URL = `/tags/${tagId}`;
            document.getElementById('deleteForm').setAttribute('action', URL);
        }
    </script>
@endsection